spring:
  application:
    name: user-service

server:
  port: 8081

custom:
  greeting: "hey bad ass rakshii, how are you"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: user-service
    prefer-ip-address: false
    instance-id: kichha

# add actuator configs

management:
  endpoints:
    web:
      exposure:
        include: "*"
